# Generated by Django 4.2.10 on 2024-06-16 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporalusermodel",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 17, 17, 30, 47, 282259, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
